### ISSUE TITLE
'neo run' fails to reload

### ISSUE THREAD

**Issue by Netherdrake** [ivpusic/neo#7]
I'm on OSX

```
~/D/g/s/b/f/brody % neo run main.go
 git/ivp/go-/hr 14:33:03 ♥[INFO] ▶ go-hotreload started.
 git/ivp/go-/hr 14:33:03 ♥[INFO] ▶ Watching for changes.
 git/ivp/go-/hr 14:33:03 ♥[INFO] ▶ Use -v flag for verbose mode
 git/ivp/neo 14:33:04 ♥[INFO] ▶ Starting application on address `127.0.0.1:3000`
 git/ivp/go-/hr 14:33:11 ✖[ERRO] ▶ Error while executing fuser command! exit status 1
 git/ivp/neo 14:33:11 ♥[INFO] ▶ Starting application on address `127.0.0.1:3000`
panic: listen tcp 127.0.0.1:3000: bind: address already in use

goroutine 1 [running]:
github.com/ivpusic/neo.(*Application).Start(0xc20804c280)
        /Users/jan/Documents/go/src/github.com/ivpusic/neo/application.go:129 +0x201
main.main()
        /Users/jan/Documents/go/src/bitbucket.org/furion/brody/main.go:17 +0x71

goroutine 2 [runnable]:
runtime.forcegchelper()
        /usr/local/Cellar/go/1.4.1/libexec/src/runtime/proc.go:90
runtime.goexit()
        /usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        /usr/local/Cellar/go/1.4.1/libexec/src/runtime/mgc0.go:82
runtime.goexit()
        /usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
        /usr/local/Cellar/go/1.4.1/libexec/src/runtime/malloc.go:712
runtime.goexit()
        /usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
```

**Comment by ivpusic** [comment]
Should be fixed by this commit https://github.com/ivpusic/go-hotreload/commit/c1f366da277fb454a659f67b5d23e9ff5d0ad5d2. Can you please confirm if it is working for you (after you get latest version)?

**Comment by Netherdrake** [comment]
I did a go get -u github.com/ivpusic/neo and I've rebuilt the neo cmd, the error didn't go away.

So I checked git log:
```
~/D/g/s/g/i/go-hotreload % git lg
*   cfed8a7 - (HEAD, origin/master, origin/HEAD, master) Merge branch 'master' of github.com:ivpusic/go-hotreload (52 minutes ago)<Ivan Pusic>
|\  
| * dfa36ab - Update README.md (3 days ago)<Ivan Pusic>
| * b515788 - improved logging (12 days ago)<ivpusic>
| * 2378158 - verbose mode improvement (12 days ago)<ivpusic>
| * cd7d80e - fix for verbose mode (13 days ago)<ivpusic>
* | c1f366d - support for mac (54 minutes ago)<Ivan Pusic>
|/  
* 267ecf7 - updated dependency (9 weeks ago)<ivpusic>
* b5d00bd - updated log messages (9 weeks ago)<ivpusic>
* daa137e - docs update (9 weeks ago)<ivpusic>
* aeb244a - readme typo (9 weeks ago)<ivpusic>
* aa31657 - added verbose mode. Added golog logger (9 weeks ago)<ivpusic>
* b54db44 - Update README.md (9 weeks ago)<Ivan Pusic>
* 14715c4 - fix for watch/ignore paths (9 weeks ago)<Ivan Pusic>
* 6e57825 - Update README.md (9 weeks ago)<Ivan Pusic>
* 67f833f - Update README.md (9 weeks ago)<Ivan Pusic>
* 4dc00d5 - Update README.md (9 weeks ago)<Ivan Pusic>
* 0a9db16 - Update README.md (9 weeks ago)<Ivan Pusic>
* 6cad053 - hr tool first commit (9 weeks ago)<ivpusic>
* 006c513 - Create README.md (9 weeks ago)<Ivan Pusic>
* 4bfcae1 - Initial commit (9 weeks ago)<Ivan Pusic>
~/D/g/s/g/i/go-hotreload % 
```

I think I'm missing something, or I forgot to update something.

**Comment by ivpusic** [comment]
try ``go get -u github.com/ivpusic/go-hotreload/hr``, and the do ``neo run main.go``. It should work.

**Comment by Netherdrake** [comment]
It works now. Thanks.
```
 git/ivp/go-/hr 19:24:51 ♥[INFO] ▶ Use -v flag for verbose mode
 git/ivp/neo 19:24:52 ♥[INFO] ▶ Starting application on address `127.0.0.1:3000`
 git/ivp/go-/hr 19:24:56 ✖[ERRO] ▶ Error while executing fuser command! exit status 1
 git/ivp/neo 19:24:57 ♥[INFO] ▶ Starting application on address `127.0.0.1:3000`
 git/ivp/neo 19:24:59 ♥[INFO] ▶ Starting application on address `127.0.0.1:3000`
 git/ivp/neo 19:25:07 ♥[INFO] ▶ Starting application on address `127.0.0.1:3000`
 git/ivp/neo 19:25:11 ♥[INFO] ▶ Starting application on address `127.0.0.1:3000`
 git/ivp/neo 19:25:13 ♥[INFO] ▶ Starting application on address `127.0.0.1:3000`
```
